version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080" 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=savannah
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=savannah
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: