version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=savannah
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=savannah
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: