apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: savannah-pos
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: kawiramwito/savannah-pos:latest  
        command: ["sh", "-c"]
        args:
          - goose -dir /migrations postgres "$DATABASE_URL" up
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 3
