apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: savannah-pos
type: Opaque
data:
  JWT_SECRET: "c3VwZXJzZWNyZXRrZXkxMjM="
  DATABASE_URL: "cG9zdGdyZXM6Ly9kZXY6c2F2YW5uYWhAZGItcG9zdGdyZXNxbDo1NDMyL3NhdmFubmFoP3NzbG1vZGU9ZGlzYWJsZQ=="
  OIDC_CLIENT_ID: "ODgxMTA3MzcxMjYtZzVyOTRnOGpuOGxhMWphaDA0YzVyaG51Y3VkN2xmdWguYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20="
  OIDC_CLIENT_SECRET: "R09DU1BYLVhZUUtjRUVGSE1jTExwUUlac2sycHFLTjdweUs="
  AFRICAS_TALKING_API_KEY: "YXRza185MzY4MTlhMmI1MTgyNDQwOWIzYTQwNDVmMDAzZTczNmM5ZjA3NTkyODY2NDMyMGUwMGNjNjY2Y2ZiODk0OTUwYjVlNmFhNTY="
  SMTP_USERNAME: "a2F3aXJhbXdpdG8zQGdtYWlsLmNvbQ=="
  SMTP_PASSWORD: "a2xjcyBmbnlvIHlwbGMgdGNjbg=="