name: CI/CD Pipeline

on:
  push:
    branches:
      - "main"

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24  

    - name: Run tests
      run: go test ./... -v

    - name: Build Docker image
      run: docker build -t savannah-pos:latest .

    - name: DockerHub login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/savannah-pos:latest
        docker tag savannah-pos:latest $IMAGE
        docker push $IMAGE

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0' 

    - name: Configure kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml