name: CI/CD Pipeline

on:
  push:
    branches: 
      - "main" 

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
    - name: Chekout  
      uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24

    - name: Build
      run: go build -v ./...